### ISSUE TITLE
No such "7 Days To Die" folder

### ISSUE THREAD

**Issue by EpyonComet** [OCB7D2D/A20BepInExPreloader#1]
Hi, the Readme says that to install the mod, I need to "Copy all files from 7 Days To Die folder into your game folder", but there is no such folder within the project. Can you please clarify what is supposed to be copied?

**Comment by mgreter** [comment]
May I ask what you try to achieve? Docs seem outdated and the necessary files for mods to use BepInEx are in the `BepInEx` folder now. This repo serves two purposes for me, one to compile my mods and secondly to hold my BepInEx setup.

**Comment by EpyonComet** [comment]
Yeah, I figured out the issues I was having with Electrical Overhaul, which were unrelated to BepinEx. But I thought I’d leave the issue up just to point out the Readme could be updated.

**Comment by EpyonComet** [comment]
Didn’t actually mean to close that, but I also don’t feel like I should re-open it, so! Either way I am good now, thanks.
